; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-c3-devkitm-1]
platform  = espressif32
board     = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
board_build.arduino.usb_cdc_on_boot = 1
upload_port = COM8
monitor_port = COM8

lib_deps =
    adafruit/Adafruit ADXL345
    adafruit/Adafruit Unified Sensor
    olikraus/U8g2

build_flags =
    -D CONFIG_SDA_PIN=8
    -D CONFIG_SCL_PIN=9
    -D CONFIG_OLED_ADDR=0x3C
    -D CONFIG_ADXL_ODR=800
    -D CONFIG_RMS_WINDOW=256
    -D CONFIG_MODBUS_PORT=502
